openapi: 3.2.0
info:
  description: Secure Docker and Kubernetes based container deployments with the NeuVector run-time security solution.
  version: 5.6.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: NeuVector EULA API
  contact:
    email: support@neuvector.com
tags:
- name: EULA
  description: End-User License Agreement
paths:
  /v1/eula:
    get:
      tags:
      - EULA
      summary: Get EULA agreement acceptance status
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTEULAData'
      operationId: getV1Eula
      x-operation-id-source: derived
    post:
      tags:
      - EULA
      summary: Accept EULA agreement
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTEULAData'
        description: EULA data
        required: true
      operationId: postV1Eula
      x-operation-id-source: derived
components:
  schemas:
    RESTEULA:
      type: object
      required:
      - accepted
      properties:
        accepted:
          type: boolean
    RESTEULAData:
      type: object
      required:
      - eula
      properties:
        eula:
          $ref: '#/components/schemas/RESTEULA'
        bootstrap_password_command:
          type: string
          description: kubectl command for retrieving bootstrap password of default admin user
        k8s_rbac_alert_message:
          type: string
          description: alert message when k8s role/rolebinding neuvector-binding-secret is not correctly configured
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Apikey
    TokenAuth:
      type: apiKey
      in: header
      name: X-Auth-Token
externalDocs:
  description: Find out more about NeuVector
  url: https://www.suse.com/products/neuvector/
