openapi: 3.2.0
info:
  description: Secure Docker and Kubernetes based container deployments with the NeuVector run-time security solution.
  version: 5.6.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: NeuVector WAF Rule API
  contact:
    email: support@neuvector.com
tags:
- name: WAF Rule
  description: Operations about waf Rule
paths:
  /v1/waf/sensor:
    get:
      tags:
      - WAF Rule
      summary: Get waf rule list
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: query
        name: scope
        required: false
        description: The default value is local which returns local waf rule list.
        schema:
          type: string
          enum:
          - local
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafSensorsData'
      operationId: getV1WafSensor
      x-operation-id-source: derived
    post:
      tags:
      - WAF Rule
      summary: Create waf sensor
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTDlpSensorConfigData'
        description: Sensor data
        required: true
      operationId: postV1WafSensor
      x-operation-id-source: derived
  /v1/waf/sensor/{name}:
    get:
      tags:
      - WAF Rule
      summary: Get waf sensor detail
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf sensor name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafSensorData'
      operationId: getV1WafSensorByName
      x-operation-id-source: derived
    patch:
      tags:
      - WAF Rule
      summary: Update a waf sensor
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf sensor name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTWafSensorConfigData'
        description: waf sensor data
        required: true
      operationId: patchV1WafSensorByName
      x-operation-id-source: derived
    delete:
      tags:
      - WAF Rule
      summary: Delete a waf sensor
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf sensor name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      operationId: deleteV1WafSensorByName
      x-operation-id-source: derived
  /v1/waf/group:
    get:
      tags:
      - WAF Rule
      summary: Get waf group list
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: query
        name: scope
        required: false
        description: The default value is local. It returns local waf group list.
        schema:
          type: string
          enum:
          - local
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafGroupsData'
      operationId: getV1WafGroup
      x-operation-id-source: derived
  /v1/waf/group/{name}:
    get:
      tags:
      - WAF Rule
      summary: Get waf group detail
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf group name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafGroupData'
      operationId: getV1WafGroupByName
      x-operation-id-source: derived
    patch:
      tags:
      - WAF Rule
      summary: Update a waf group
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf group name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTWafGroupConfigData'
        description: waf group data
        required: true
      operationId: patchV1WafGroupByName
      x-operation-id-source: derived
  /v1/waf/rule:
    get:
      tags:
      - WAF Rule
      summary: Get waf rule list
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafRulesData'
      operationId: getV1WafRule
      x-operation-id-source: derived
  /v1/waf/rule/{name}:
    get:
      tags:
      - WAF Rule
      summary: Get waf rule detail
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: waf rule name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTWafRuleData'
      operationId: getV1WafRuleByName
      x-operation-id-source: derived
components:
  schemas:
    RESTWafRuleData:
      type: object
      required:
      - rule
      properties:
        rule:
          $ref: '#/components/schemas/RESTWafRuleDetail'
    RESTWafSetting:
      type: object
      required:
      - name
      - action
      - exist
      - cfg_type
      properties:
        name:
          type: string
          example: test
        action:
          type: string
          example: deny
        exist:
          type: boolean
          example: true
        comment:
          type: string
          example: ''
        cfg_type:
          type: string
          enum:
          - user_created
          - ground
    RESTDlpSensorConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTDlpSensorConfig'
    RESTWafRuleDetail:
      type: object
      required:
      - sensors
      - rules
      properties:
        sensors:
          type: array
          items:
            type: string
            example: test
        rules:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
    RESTWafRulesData:
      type: object
      required:
      - rules
      properties:
        rules:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
    RESTCriteriaEntry:
      type: object
      required:
      - key
      - value
      - op
      properties:
        key:
          type: string
          example: pattern
        value:
          type: string
          example: '[0-9]'
        op:
          type: string
          example: regex
    RESTWafSensorData:
      type: object
      required:
      - sensor
      properties:
        sensor:
          $ref: '#/components/schemas/RESTWafSensor'
    RESTWafSensor:
      type: object
      required:
      - name
      - groups
      - rules
      - comment
      - predefine
      - cfg_type
      properties:
        name:
          type: string
          example: test4321546242574254672462572452615362453
        groups:
          type: array
          items:
            type: string
            example: nv.kube-proxy.kube-system
        rules:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
        comment:
          type: string
          example: ''
        predefine:
          type: boolean
          example: false
        cfg_type:
          type: string
          enum:
          - user_created
          - ground
    RESTWafGroupConfig:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          example: ''
        status:
          type: boolean
          example: false
        delete:
          type: array
          items:
            type: string
            example: ''
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafConfig'
        replace:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafConfig'
    RESTWafRule:
      type: object
      required:
      - name
      - id
      - patterns
      - cfg_type
      properties:
        name:
          type: string
          example: test
        id:
          type: integer
          format: uint32
          example: 40003
        patterns:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafCriteriaEntry'
        cfg_type:
          type: string
          enum:
          - user_created
          - ground
    RESTWafCriteriaEntry:
      type: object
      required:
      - key
      - value
      - op
      properties:
        key:
          type: string
          example: pattern
        value:
          type: string
          example: '[0-9]'
        op:
          type: string
          example: regex
        context:
          type: string
          example: packet
    RESTWafSensorConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTWafSensorConfig'
    RESTWafConfig:
      type: object
      required:
      - name
      - action
      properties:
        name:
          type: string
          example: ''
        action:
          type: string
          example: ''
        comment:
          type: string
          example: ''
    RESTDlpRule:
      type: object
      required:
      - name
      - id
      - patterns
      - cfg_type
      properties:
        name:
          type: string
          example: testrule413251424153561246153614615462515134635
        id:
          type: integer
          format: uint32
          example: 4001
        patterns:
          type: array
          items:
            $ref: '#/components/schemas/RESTCriteriaEntry'
        cfg_type:
          type: string
          enum:
          - user_created
          - ground
    RESTWafGroupsData:
      type: object
      required:
      - waf_groups
      properties:
        waf_groups:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafGroup'
    RESTWafGroupData:
      type: object
      required:
      - waf_group
      properties:
        waf_group:
          $ref: '#/components/schemas/RESTWafGroup'
    RESTWafSensorConfig:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          example: ''
        change:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
        delete:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
        rules:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafRule'
        comment:
          type: string
          example: ''
    RESTWafSensorsData:
      type: object
      required:
      - sensors
      properties:
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafSensor'
    RESTWafGroup:
      type: object
      required:
      - name
      - status
      - sensors
      - cfg_type
      properties:
        name:
          type: string
          example: nv.kube-proxy.kube-system
        status:
          type: boolean
          example: true
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/RESTWafSetting'
        cfg_type:
          type: string
          enum:
          - user_created
          - ground
    RESTWafGroupConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTWafGroupConfig'
    RESTDlpSensorConfig:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          example: sensor.creditcard
        change:
          type: array
          items:
            $ref: '#/components/schemas/RESTDlpRule'
        delete:
          type: array
          items:
            $ref: '#/components/schemas/RESTDlpRule'
        rules:
          type: array
          items:
            $ref: '#/components/schemas/RESTDlpRule'
        comment:
          type: string
          example: Sensor for Credit Card detection
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Apikey
    TokenAuth:
      type: apiKey
      in: header
      name: X-Auth-Token
externalDocs:
  description: Find out more about NeuVector
  url: https://www.suse.com/products/neuvector/
