openapi: 3.2.0
info:
  description: Secure Docker and Kubernetes based container deployments with the NeuVector run-time security solution.
  version: 5.6.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: NeuVector Enforcer API
  contact:
    email: support@neuvector.com
tags:
- name: Enforcer
  description: Operations about Enforcer
paths:
  /v1/enforcer:
    get:
      tags:
      - Enforcer
      summary: Get a list of enforcers
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTAgentsData'
      operationId: getV1Enforcer
      x-operation-id-source: derived
  /v1/enforcer/{id}:
    get:
      tags:
      - Enforcer
      summary: Show enforcer
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: id
        description: Enforcer ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTAgentData'
      operationId: getV1EnforcerById
      x-operation-id-source: derived
    patch:
      tags:
      - Enforcer
      summary: Update enforcer
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: id
        description: Enforcer ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTAgentConfigData'
        description: Enforcer update data
        required: true
      operationId: patchV1EnforcerById
      x-operation-id-source: derived
  /v1/enforcer/{id}/stats:
    get:
      tags:
      - Enforcer
      summary: Get enforcer statistics
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: id
        description: Enforcer ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTAgentStatsData'
      operationId: getV1EnforcerByIdStats
      x-operation-id-source: derived
  /v1/enforcer/{id}/config:
    get:
      tags:
      - Enforcer
      summary: Enforcer get configure
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: id
        description: Enforcer ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTAgentConfigData'
      operationId: getV1EnforcerByIdConfig
      x-operation-id-source: derived
components:
  schemas:
    RESTStats:
      type: object
      required:
      - interval
      - total
      - span_1
      - span_12
      - span_60
      properties:
        interval:
          type: integer
          format: uint32
          example: 5
        total:
          $ref: '#/components/schemas/RESTMetry'
        span_1:
          $ref: '#/components/schemas/RESTMetry'
        span_12:
          $ref: '#/components/schemas/RESTMetry'
        span_60:
          $ref: '#/components/schemas/RESTMetry'
    RESTAgentStatsData:
      type: object
      required:
      - id
      - read_at
      - stats
      properties:
        id:
          type: string
          example: 541386aa8e36fe113593cc0dc6678b7d2a
        read_at:
          type: string
          format: date-time
          example: 2018-01-18 07:20:15+00:00
        stats:
          $ref: '#/components/schemas/RESTStats'
    RESTAgentsData:
      type: object
      required:
      - enforcers
      properties:
        enforcers:
          type: array
          items:
            $ref: '#/components/schemas/RESTAgent'
    RESTAgent:
      type: object
      required:
      - id
      - name
      - display_name
      - host_name
      - host_id
      - version
      - labels
      - domain
      - pid_mode
      - network_mode
      - created_at
      - started_at
      - joined_at
      - memory_limit
      - cpus
      - cluster_ip
      - connection_state
      - disconnected_at
      properties:
        id:
          type: string
          example: 924ccbbfcac6842e7370305bc51f4594764314f6
        name:
          type: string
          example: allinone
        display_name:
          type: string
          example: allinone
        host_name:
          type: string
          example: ubuntu64
        host_id:
          type: string
          example: 2AU7:TIEN:O5KX:QK56:LFQP:IJSV:FXBN:QJV7
        version:
          type: string
          example: 0.1.0
        labels:
          type: object
          description: map key is string type
          additionalProperties:
            type: string
          example:
            com.docker.compose.service: allinone
        domain:
          type: string
          example: ''
        pid_mode:
          type: string
          example: ''
        network_mode:
          type: string
          example: host
        created_at:
          type: string
          format: date-time
          example: 2018-01-23 21:14:31+00:00
        started_at:
          type: string
          format: date-time
          example: 2018-01-23 21:14:31+00:00
        joined_at:
          type: string
          format: date-time
          example: 2018-01-23 21:14:55+00:00
        memory_limit:
          type: integer
          format: int64
          example: 0
        cpus:
          type: string
          example: ''
        cluster_ip:
          type: string
          example: 10.1.5.1
        connection_state:
          type: string
          example: connected
        disconnected_at:
          type: string
          example: ''
    RESTAgentConfig:
      type: object
      properties:
        debug:
          type: array
          items:
            type: string
          example:
          - packet
          - log
          - parser
          - tcp
          - session
          - timer
          - error
        disable_nvprotect:
          type: boolean
          example: false
        disable_kvcctl:
          type: boolean
          example: false
    RESTAgentData:
      type: object
      required:
      - enforcer
      properties:
        enforcer:
          $ref: '#/components/schemas/RESTAgent'
    RESTAgentConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTAgentConfig'
    RESTMetry:
      type: object
      required:
      - cpu
      - memory
      - session_in
      - session_out
      - packet_in
      - packet_out
      - byte_in
      - byte_out
      properties:
        cpu:
          type: number
          format: float64
          example: 1
        memory:
          type: integer
          format: uint64
          example: 2089816064
        session_in:
          type: integer
          format: uint32
          example: 0
        session_out:
          type: integer
          format: uint32
          example: 0
        cur_session_in:
          type: integer
          format: uint32
          example: 1
        cur_session_out:
          type: integer
          format: uint32
          example: 1
        packet_in:
          type: integer
          format: uint64
          example: 0
        packet_out:
          type: integer
          format: uint64
          example: 0
        byte_in:
          type: integer
          format: uint64
          example: 0
        byte_out:
          type: integer
          format: uint64
          example: 0
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Apikey
    TokenAuth:
      type: apiKey
      in: header
      name: X-Auth-Token
externalDocs:
  description: Find out more about NeuVector
  url: https://www.suse.com/products/neuvector/
