swagger: '2.0'
info:
  description: Secure Docker and Kubernetes based container deployments with the NeuVector run-time security solution.
  version: 5.6.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: NeuVector Remote Repository API
  contact:
    email: support@neuvector.com
schemes:
- https
tags:
- name: Remote Repository
paths:
  /v1/system/config/remote_repository:
    post:
      tags:
      - Remote Repository
      summary: Create a remote repository.
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Initial Configuration
        required: true
        schema:
          $ref: '#/definitions/RESTRemoteRepository'
      responses:
        '200':
          description: Created the remote repository.
  /v1/system/config/remote_repository/{alias}:
    patch:
      tags:
      - Remote Repository
      summary: Update a remote repository.
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      consumes:
      - application/json
      parameters:
      - in: path
        name: alias
        description: The alias of the remote repository to update.
        required: true
        type: string
      - in: body
        name: body
        description: Configuration fields to update
        required: true
        schema:
          $ref: '#/definitions/RESTRemoteRepositoryConfigData'
      responses:
        '200':
          description: Updated the remote repository.
definitions:
  RESTRemoteRepository_GitHubConfigConfig:
    type: object
    properties:
      repository_owner_username:
        type: string
        example: myuser
      repository_name:
        type: string
        example: myrepo
      repository_branch_name:
        type: string
        example: main
      personal_access_token:
        type: string
        example: <access token from GitHub>
      personal_access_token_committer_name:
        type: string
        example: myuser
      personal_access_token_committer_email:
        type: string
        example: myuser@example.com
  RESTRemoteRepositoryConfigData:
    type: object
    required:
    - config
    properties:
      config:
        $ref: '#/definitions/RESTRemoteRepositoryConfig'
  RESTRemoteRepo_GitHubConfig:
    type: object
    required:
    - repository_owner_username
    - repository_name
    - repository_branch_name
    - personal_access_token
    - personal_access_token_committer_name
    - personal_access_token_committer_email
    properties:
      repository_owner_username:
        type: string
        example: myuser
      repository_name:
        type: string
        example: myrepo
      repository_branch_name:
        type: string
        example: main
      personal_access_token:
        type: string
        example: <access token from GitHub>
      personal_access_token_committer_name:
        type: string
        example: myuser
      personal_access_token_committer_email:
        type: string
        example: myuser@example.com
  RESTRemoteRepositoryConfig:
    type: object
    required:
    - nickname
    properties:
      nickname:
        type: string
        example: default
      comment:
        type: string
      enable:
        type: boolean
        example: true
      github_configuration:
        $ref: '#/definitions/RESTRemoteRepository_GitHubConfigConfig'
  RESTRemoteRepository:
    type: object
    required:
    - nickname
    - provider
    - github_configuration
    properties:
      nickname:
        type: string
        example: default
      provider:
        type: string
        description: currently only github is supported
        example: github
      comment:
        type: string
      enable:
        type: boolean
        example: true
      github_configuration:
        $ref: '#/definitions/RESTRemoteRepo_GitHubConfig'
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-Auth-Apikey
  TokenAuth:
    type: apiKey
    in: header
    name: X-Auth-Token
externalDocs:
  description: Find out more about NeuVector
  url: https://www.suse.com/products/neuvector/
