openapi: 3.2.0
info:
  description: Secure Docker and Kubernetes based container deployments with the NeuVector run-time security solution.
  version: 5.6.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: NeuVector Namespace API
  contact:
    email: support@neuvector.com
tags:
- name: Namespace
  description: Operations about Namespace
paths:
  /v1/domain:
    get:
      tags:
      - Namespace
      summary: Get Namespace list
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RESTDomainsData'
      operationId: getV1Domain
      x-operation-id-source: derived
    patch:
      tags:
      - Namespace
      summary: Configure Namespace setting
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTDomainConfigData'
        description: Namespace update data
        required: true
      operationId: patchV1Domain
      x-operation-id-source: derived
  /v1/domain/{name}:
    patch:
      tags:
      - Namespace
      summary: Update namespace
      security:
      - ApiKeyAuth: []
      - TokenAuth: []
      parameters:
      - in: path
        name: name
        description: namespace name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RESTDomainEntryConfigData'
        description: Namespace update data
        required: true
      operationId: patchV1DomainByName
      x-operation-id-source: derived
components:
  schemas:
    RESTDomainEntryConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTDomainEntryConfig'
    RESTDomainConfigData:
      type: object
      required:
      - config
      properties:
        config:
          $ref: '#/components/schemas/RESTDomainConfig'
    RESTDomainConfig:
      type: object
      properties:
        tag_per_domain:
          type: boolean
          example: true
    RESTDomain:
      type: object
      required:
      - name
      - workloads
      - running_workloads
      - running_pods
      - services
      - tags
      - labels
      properties:
        name:
          type: string
          example: iperfspace
        workloads:
          type: integer
          example: 14
        running_workloads:
          type: integer
          example: 14
        running_pods:
          type: integer
          example: 7
        services:
          type: integer
          example: 3
        tags:
          type: array
          items:
            type: string
          example:
          - ''
        labels:
          type: object
          description: map key is string type
          additionalProperties:
            type: string
          example:
            ns.env-1: production
    RESTDomainsData:
      type: object
      required:
      - domains
      - tag_per_domain
      properties:
        domains:
          type: array
          items:
            $ref: '#/components/schemas/RESTDomain'
        tag_per_domain:
          type: boolean
          example: false
    RESTDomainEntryConfig:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          example: iperfspace
        tags:
          type: array
          items:
            type: string
          example:
          - ''
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth-Apikey
    TokenAuth:
      type: apiKey
      in: header
      name: X-Auth-Token
externalDocs:
  description: Find out more about NeuVector
  url: https://www.suse.com/products/neuvector/
